package com.project.numble.application.auth.exception;

public class UserAlreadySignOutException extends RuntimeException {

    public UserAlreadySignOutException(Throwable cause) {
        super(cause);
    }
}
